services:
  product_service:
    build:
      context: ./product_service
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  order_service:
    build:
      context: ./order_service
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  user_service:
    build:
      context: ./user_service  # Ensure this directory exists
    ports:
      - "5000:5000"  # Modify as per actual service port in `user_serviceapp.py`
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
